%% PREAMBLE
close all;
clear variables;
clc;

% Set default formatting properties for figures using LaTeX formatting
set(groot, 'defaultTextInterpreter', 'Latex');
set(groot, 'defaultLegendInterpreter', 'Latex');
set(groot, 'defaultAxesTickLabelInterpreter','latex');
set(groot, 'defaultLegendInterpreter','latex');
set(groot, 'defaultTextFontSize', 12);
set(groot, 'defaultAxesFontSize', 16);
set(groot, 'defaultLineLineWidth', 2);
set(groot, 'defaultFigureColor', 'white');

%% Initializing and Loading Data
leg_vec = ["High Flex", "Low Flex", "Rigid"];
color_vec = ["#0072BD", "#D95319", "#EDB120"];  % String array


%Column 1 is scenario, 2 is encounter location, 3 is circulation, 4 ,is
%CL1, 5 is CL2, 6 is r, 7 is CL1 std err, 8 is CL2 std err, 9 is peak RMS,
%10 is noise RMS
rigid = readmatrix('C:\Users\Christopher\Desktop\Good Thesis Data\MaxData\RigidMaxData.csv');
highFlex = readmatrix('C:\Users\Christopher\Desktop\Good Thesis Data\MaxData\HighFlexMaxData.csv');
lowFlex = readmatrix('C:\Users\Christopher\Desktop\Good Thesis Data\MaxData\LowFlexMaxData.csv');

%Plotting

%% Encounter location
figure(1)
ar1 = subplot(1, 2, 1);
hold(ar1, 'on');
xlabel(ar1, 'Encounter Location $y^* = y/L$');
ylabel(ar1, '$C_{L, max}$');
title(ar1, 'Maximum Lift');
%xlim(ar1, [10 40]);
ylim(ar1, [-0.8 1.1]);
grid(ar1, 'on');
errorbar(highFlex(:,2), highFlex(:,5), highFlex(:,8), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(1), ...
    'MarkerEdgeColor', color_vec(1), ...
    'Color', color_vec(1), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(1));
errorbar(lowFlex(:,2), lowFlex(:,5), lowFlex(:,8), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(2), ...
    'MarkerEdgeColor', color_vec(2), ...
    'Color', color_vec(2), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(2));
errorbar(rigid(:,2), rigid(:,5), rigid(:,8), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(3), ...
    'MarkerEdgeColor', color_vec(3), ...
    'Color', color_vec(3), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(3));
legend('show')
hold(ar1, 'off')

ar2 = subplot(1, 2, 2);
hold(ar2, 'on');
xlabel(ar2, 'Encounter Location $y^* = y/L$');
ylabel(ar2, '$r^*_{max}$');
title(ar2, 'Maximum Laser Displacement');
%xlim(ar2, [10 40]);
%ylim(ar2, [-0.4 0.4]);
grid(ar2, 'on');
errorbar(highFlex(:,2), highFlex(:,9), highFlex(:,10), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(1), ...
    'MarkerEdgeColor', color_vec(1), ...
    'Color', color_vec(1), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(1));
errorbar(lowFlex(:,2), lowFlex(:,9), lowFlex(:,10), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(2), ...
    'MarkerEdgeColor', color_vec(2), ...
    'Color', color_vec(2), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(2));
legend('show')
hold(ar2, 'off')


%% Circulation
figure(2)

ag1 = subplot(1, 2, 1);
hold(ag1, 'on');
xlabel(ag1, 'Circulation $\Gamma^* = \overline{\Gamma}/cU$');
ylabel(ag1, '$C_{L, max}$');
title(ag1, 'Maximum Lift');
%xlim(ag1, [10 40]);
ylim(ag1, [-0.8 1.1]);
grid(ag1, 'on');
errorbar(highFlex(:,3), highFlex(:,5), highFlex(:,8), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(1), ...
    'MarkerEdgeColor', color_vec(1), ...
    'Color', color_vec(1), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(1));
errorbar(lowFlex(:,3), lowFlex(:,5), lowFlex(:,8), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(2), ...
    'MarkerEdgeColor', color_vec(2), ...
    'Color', color_vec(2), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(2));
errorbar(rigid(:,3), rigid(:,5), rigid(:,8), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(3), ...
    'MarkerEdgeColor', color_vec(3), ...
    'Color', color_vec(3), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(3));
legend('show')
hold(ag1, 'off')

ag2 = subplot(1, 2, 2);
hold(ag2, 'on');
xlabel(ag2, 'Circulation $\Gamma^* = \overline{\Gamma}/cU$');
ylabel(ag2, '$r^*_{max}$');
title(ag2, 'Maximum Laser Displacement');
%xlim(ag2, [10 40]);
%ylim(ag2, [-0.4 0.4]);
grid(ag2, 'on');
errorbar(highFlex(:,3), highFlex(:,9), highFlex(:,10), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(1), ...
    'MarkerEdgeColor', color_vec(1), ...
    'Color', color_vec(1), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(1));
errorbar(lowFlex(:,3), lowFlex(:,9), lowFlex(:,10), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(2), ...
    'MarkerEdgeColor', color_vec(2), ...
    'Color', color_vec(2), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(2));
legend('show')
hold(ag2, 'off')

%% Encounter Location AND Circulation

figure(3)
ab1 = subplot(1, 2, 1);
hold(ab1, 'on');
xlabel(ab1, '$\Gamma^* /y^*$');
ylabel(ab1, '$C_{L, max}$');
title(ab1, 'Maximum Lift');
%xlim(ab1, [10 40]);
ylim(ab1, [-0.8 1.1]);
grid(ab1, 'on');
errorbar(highFlex(:,3)./highFlex(:,2), highFlex(:,5), highFlex(:,8), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(1), ...
    'MarkerEdgeColor', color_vec(1), ...
    'Color', color_vec(1), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(1));
errorbar(lowFlex(:,3)./lowFlex(:,2), lowFlex(:,5), lowFlex(:,8), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(2), ...
    'MarkerEdgeColor', color_vec(2), ...
    'Color', color_vec(2), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(2));
errorbar(rigid(:,3)./rigid(:,2), rigid(:,5), rigid(:,8), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(3), ...
    'MarkerEdgeColor', color_vec(3), ...
    'Color', color_vec(3), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(3));
legend('show')
hold(ab1, 'off')

ab2 = subplot(1, 2, 2);
hold(ab2, 'on');
xlabel(ab2, '$\Gamma^* /y^*$');
ylabel(ab2, '$r^*_{max}$');
title(ab2, 'Maximum Laser Displacement');
%xlim(ab2, [10 40]);
%ylim(ab2, [-0.4 0.4]);
grid(ab2, 'on');

errorbar(highFlex(:,3)./highFlex(:,2), highFlex(:,9), highFlex(:,10), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(1), ...
    'MarkerEdgeColor', color_vec(1), ...
    'Color', color_vec(1), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(1));
errorbar(lowFlex(:,3)./lowFlex(:,2), lowFlex(:,9), lowFlex(:,10), ...
    'o', ...  % Circle marker
    'MarkerSize', 6, ...
    'MarkerFaceColor', color_vec(2), ...
    'MarkerEdgeColor', color_vec(2), ...
    'Color', color_vec(2), ...
    'LineStyle', 'none', ...
    'DisplayName', leg_vec(2));
legend('show')
hold(ab2, 'off')

